[package]
name = "pennereq"
version = "0.1.0"
authors = ["arturo castro <arturo@openframeworks.cc>"]
repository = "https://github.com/arturoc/pennereq-rs"
description = "Port of the Penner easing equations to rust"
license="BSD-2-Clause"
readme="README.md"

[dependencies]
num="0.1"
